// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCESD67BYe9qPr1XGiEfvm3oUsqWodvRJw',
    appId: '1:45791923833:web:2aba95f57c8e9dfa6b8ea8',
    messagingSenderId: '45791923833',
    projectId: 'empathy-exchange-473417',
    authDomain: 'empathy-exchange-473417.firebaseapp.com',
    storageBucket: 'empathy-exchange-473417.firebasestorage.app',
    measurementId: 'G-WB44LX8J7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESD67BYe9qPr1XGiEfvm3oUsqWodvRJw',
    appId: '1:45791923833:android:2aba95f57c8e9dfa6b8ea8',
    messagingSenderId: '45791923833',
    projectId: 'empathy-exchange-473417',
    storageBucket: 'empathy-exchange-473417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCESD67BYe9qPr1XGiEfvm3oUsqWodvRJw',
    appId: '1:45791923833:ios:2aba95f57c8e9dfa6b8ea8',
    messagingSenderId: '45791923833',
    projectId: 'empathy-exchange-473417',
    storageBucket: 'empathy-exchange-473417.firebasestorage.app',
    iosClientId: '45791923833-2aba95f57c8e9dfa6b8ea8.apps.googleusercontent.com',
    iosBundleId: 'com.example.empathy_exchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCESD67BYe9qPr1XGiEfvm3oUsqWodvRJw',
    appId: '1:45791923833:ios:2aba95f57c8e9dfa6b8ea8',
    messagingSenderId: '45791923833',
    projectId: 'empathy-exchange-473417',
    storageBucket: 'empathy-exchange-473417.firebasestorage.app',
    iosClientId: '45791923833-2aba95f57c8e9dfa6b8ea8.apps.googleusercontent.com',
    iosBundleId: 'com.example.empathy_exchange',
  );
}

